# Embed a binary file as a C byte array (browser backend guest bytes).
# Usage: cmake -DINPUT=<wasm> -DOUTPUT=<header> -DSYMBOL=<name> -P embed_wasm.cmake
file(READ "${INPUT}" bytes HEX)
string(REGEX MATCHALL "([0-9a-f][0-9a-f])" pairs "${bytes}")
set(body "")
set(i 0)
foreach(pair IN LISTS pairs)
  string(APPEND body "0x${pair},")
  math(EXPR i "${i} + 1")
  math(EXPR wrapped "${i} % 20")
  if(wrapped EQUAL 0)
    string(APPEND body "\n")
  endif()
endforeach()
file(WRITE "${OUTPUT}"
     "/* Generated by embed_wasm.cmake -- do not edit. */\n"
     "#pragma once\n"
     "#include <cstddef>\n"
     "inline const unsigned char ${SYMBOL}[] = {\n${body}};\n"
     "inline const std::size_t ${SYMBOL}_bytes = sizeof ${SYMBOL};\n")
