/*
 * BrowserWasmBackend module-loading smoke (dynamic-loading-all-platforms todo 8).
 *
 * Emscripten-only executable, booted headlessly by scripts/smoke_web.mjs
 * (same --variant CLI as todo 5). Exercises the REAL loader path —
 * load_portable_wasm_plugin_binary -> BrowserWasmBackend::instantiate ->
 * query_portable_wasm_plugin (descriptor decode) -> activate (host imports
 * bound, configure, start) — then invokes the guest's annotated export
 * through the backend and asserts the returned value, plus the invalid-bytes
 * failure path (BackendFailure issue, no crash).
 *
 * Todo 10 extension: the annotated exports are invoked through the GENERIC
 * DESCRIPTOR-DRIVEN dispatcher (browser_wasm_invoke_typed_export). The guest's
 * annotation table is read live from the instance memory (the extraction
 * tool's resolution algorithm, in miniature), validated, and its decoded
 * marshaling descriptors drive the calls — tag -> extract -> manifest ->
 * dispatcher end to end, no per-module glue.
 *
 * The embedded guest bytes are staged onto the emscripten MEMFS so the
 * production file-based loader runs verbatim; no loader code changed.
 *
 * Web builds compile without exceptions and without a test framework
 * (BUILD_TESTING is OFF on emscripten), so failures print a FATAL marker and
 * return nonzero; the node runner treats a nonzero exit and the missing
 * success marker as a failed smoke.
 */
#include "browser_wasm_backend.hpp"

#include "memory/memory_manager.hpp"
#include "memory/web_shim.hpp"

#include "modules/module_manifest.hpp"
#include "plugins/wasm_runtime.hpp"

#include <mobagen/module/module_abi.h>
#include <mobagen/plugin/wasm_abi.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <span>
#include <string>
#include <vector>

/* Generated by the guest-build step: mobagen_smoke_guest_wasm.h */
#include "mobagen_smoke_guest_wasm.h"

/* Todo 16: the emcc-built QuickJS scripting guest (same embed pipeline). */
#include "mobagen_quickjs_guest_wasm.h"
/* Todo 17: the emcc-built Lua scripting guest (same embed pipeline). */
#include "mobagen_lua_guest_wasm.h"

namespace {

  int failures = 0;

  void check(bool ok, const char* what) {
    if (ok) {
      std::printf("[browser-smoke] PASS: %s\n", what);
    } else {
      std::printf("[browser-smoke] FATAL: %s\n", what);
      ++failures;
    }
  }

  bool stage_file(const std::filesystem::path& path, std::span<const std::byte> bytes) {
    std::error_code error;
    std::filesystem::create_directories(path.parent_path(), error);
    std::ofstream out{path, std::ios::binary | std::ios::trunc};
    if (!out.is_open()) return false;
    out.write(reinterpret_cast<const char*>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
    out.close();
    return out.good();
  }

  std::uint32_t read_guest_u32(const std::byte* memory, std::uint32_t offset) {
    const auto* bytes = reinterpret_cast<const unsigned char*>(memory) + offset;
    return static_cast<std::uint32_t>(bytes[0]) | (static_cast<std::uint32_t>(bytes[1]) << 8U) | (static_cast<std::uint32_t>(bytes[2]) << 16U)
           | (static_cast<std::uint32_t>(bytes[3]) << 24U);
  }

  /*
   * Reads the guest's annotation table from its live linear memory (the
   * mirror view). Mirrors the extraction tool's shape-(b) resolution: the
   * exported global mobagen_module_exports_v1 points (possibly through one
   * indirection) at the table; here the instance memory is already mapped,
   * so the table offset is read directly from the canonical symbol's bytes.
   */
  bool read_annotation_exports(const std::byte* memory, std::size_t memory_bytes, std::vector<mobagen::modules::ModuleManifestExport>& out) {
    if (memory == nullptr || memory_bytes < 16) return false;
    /* The published global's storage sits in the guest's data segment; its
       VALUE is the table offset. Locate it by scanning for the table header
       itself: exactly one MobagenModuleExportTableV1 header with the kind
       magic exists in this guest. */
    for (std::size_t offset = 0; offset + 16U <= memory_bytes; offset += 4U) {
      if (read_guest_u32(memory, static_cast<std::uint32_t>(offset)) != MOBAGEN_MODULE_TABLE_V1) continue;
      const auto abi_version = read_guest_u32(memory, static_cast<std::uint32_t>(offset) + 4);
      const auto entry_count = read_guest_u32(memory, static_cast<std::uint32_t>(offset) + 8);
      if (abi_version != MOBAGEN_MODULE_ABI_VERSION || entry_count == 0 || entry_count > 16) continue;
      const std::size_t first_entry = offset + 16U;
      if (first_entry + entry_count * 16U > memory_bytes) return false;
      for (std::uint32_t index = 0; index < entry_count; ++index) {
        const auto entry = first_entry + index * 16U;
        const auto name_offset = read_guest_u32(memory, static_cast<std::uint32_t>(entry));
        const auto signature_id = read_guest_u32(memory, static_cast<std::uint32_t>(entry) + 8);
        if (name_offset == 0 || name_offset >= memory_bytes) return false;
        std::string name;
        for (std::uint32_t cursor = name_offset; cursor < memory_bytes && name.size() < 128; ++cursor) {
          const auto character = static_cast<char>(memory[cursor]);
          if (character == '\0') break;
          name.push_back(character);
        }
        if (name.empty()) return false;
        mobagen::modules::ModuleExportMarshaling decoded;
        if (!mobagen::modules::decode_module_export_marshaling(signature_id, decoded)) return false;
        out.push_back({std::move(name), signature_id, decoded});
      }
      return !out.empty();
    }
    return false;
  }

}  // namespace

int main() {
  using namespace mobagen::plugins;

  BrowserWasmBackend backend;

  /* 1. Happy path: the production loader pipeline over the embedded guest. */
  const std::span<const std::byte> guest{reinterpret_cast<const std::byte*>(mobagen_smoke_guest_wasm), mobagen_smoke_guest_wasm_bytes};
  const std::filesystem::path guest_path{"/mobagen-smoke/reference.plugin.wasm"};
  check(stage_file(guest_path, guest), "reference guest staged onto MEMFS");

  auto loaded = load_portable_wasm_plugin_binary(guest_path, backend);
  check(loaded.ok(), "reference guest loaded through BrowserWasmBackend (sync instantiate + descriptor query)");
  if (!loaded.ok() && !loaded.issues.empty()) {
    std::printf("[browser-smoke]   load issue: %s\n", loaded.issues.front().message.c_str());
  }
  if (loaded.ok() && loaded.plugin.has_value()) {
    check(loaded.plugin->provider().id == "mobagen.browser-smoke.default", "queried provider id matches the guest descriptor");

    auto instance = loaded.plugin->take_instance();
    check(instance != nullptr, "loaded instance taken for direct export invocation");

    /* Invoke the annotated export through the backend and assert the value. */
    std::uint32_t result = 0;
    const int called = browser_wasm_call_named_export(*instance, "mobagen_smoke_add", 20, 22, &result);
    check(called == 0, "mobagen_smoke_add invoked through the backend");
    check(called == 0 && result == 42, "mobagen_smoke_add(20, 22) returned 42");

    /* 1b. Todo 10: read the annotation table live and dispatch through the
       generic descriptor-driven marshaller. */
    std::vector<mobagen::modules::ModuleManifestExport> annotated;
    const auto memory = instance->memory();
    check(read_annotation_exports(memory.data(), memory.size(), annotated), "annotation table read from live guest memory");
    if (!annotated.empty()) {
      const auto* mul = static_cast<const mobagen::modules::ModuleManifestExport*>(nullptr);
      const auto* span_sum = static_cast<const mobagen::modules::ModuleManifestExport*>(nullptr);
      for (const auto& entry : annotated) {
        if (entry.name == "mobagen_smoke_mul") mul = &entry;
        if (entry.name == "mobagen_smoke_span_sum") span_sum = &entry;
      }
      check(mul != nullptr && mul->marshaling.has_value(), "mobagen_smoke_mul descriptor decoded from the annotation table");

      if (mul != nullptr && mul->marshaling.has_value()) {
        std::array<std::uint32_t, 2> result_cells{};
        const std::array arguments{std::uint32_t{6}, std::uint32_t{7}};
        const auto dispatched = browser_wasm_invoke_typed_export(*instance, mul->name, *mul->marshaling, arguments, result_cells);
        check(dispatched == 0, "mobagen_smoke_mul dispatched through the generic descriptor marshaller");
        check(dispatched == 0 && result_cells[0] == 42, "mobagen_smoke_mul(6, 7) returned 42 through the descriptor path");
      }

      if (span_sum != nullptr && span_sum->marshaling.has_value()) {
        /* A span cell names a guest-memory (offset,size) pair. Stage the pair
           at a real linear offset and five data bytes after it. */
        auto writable = instance->writable_memory();
        check(writable.size() >= 4096, "guest memory writable for span staging");
        if (writable.size() >= 4096) {
          const std::uint32_t pair_offset = 2048;
          const std::uint32_t data_offset = 2064;
          for (std::size_t index = 0; index < 4; ++index) {
            writable[pair_offset + index] = std::byte{0};
          }
          writable[pair_offset + 0] = std::byte{static_cast<std::uint8_t>(data_offset & 0xffU)};
          writable[pair_offset + 1] = std::byte{static_cast<std::uint8_t>((data_offset >> 8U) & 0xffU)};
          writable[pair_offset + 4] = std::byte{5};
          for (std::size_t index = 0; index < 5; ++index) writable[data_offset + index] = std::byte{2};
          std::array<std::uint32_t, 2> result_cells{};
          const std::array<std::uint32_t, 1> span_cells{pair_offset};
          const auto dispatched = browser_wasm_invoke_typed_export(*instance, span_sum->name, *span_sum->marshaling, span_cells, result_cells);
          check(dispatched == 0, "mobagen_smoke_span_sum dispatched through the descriptor marshaller");
          check(dispatched == 0 && result_cells[0] == 10, "mobagen_smoke_span_sum({2,2,2,2,2}) returned 10 through the descriptor path");
        }
      }

      /* Out-of-bounds span cells are rejected before any call. */
      if (span_sum != nullptr && span_sum->marshaling.has_value()) {
        std::array<std::uint32_t, 2> result_cells{};
        const std::array<std::uint32_t, 1> out_of_bounds{0xffff0000U};
        const auto rejected = browser_wasm_invoke_typed_export(*instance, span_sum->name, *span_sum->marshaling, out_of_bounds, result_cells);
        check(rejected == -3, "out-of-bounds span cells rejected before the call");
      }
    }

    auto activated = activate_portable_wasm_plugin(std::move(instance));
    check(activated.ok(), "guest activated (host imports bound, configure + start)");
    if (!activated.ok() && !activated.issues.empty()) {
      std::printf("[browser-smoke]   activation issue: %s\n", activated.issues.front().message.c_str());
    } else if (activated.ok() && activated.activation != nullptr) {
      auto quiesced = activated.activation->quiesce();
      auto stopped = quiesced.ok() ? activated.activation->stop() : quiesced;
      check(stopped.ok(), "guest quiesced + stopped cleanly");
    }
  }

  /* 2. Failure path: invalid wasm bytes must surface a load issue, not crash.
     Valid 8-byte header + garbage body trips the browser compile — the exact
     class of throw the backend must map to BackendFailure. */
  static const std::byte invalid_bytes[]{std::byte{0x00}, std::byte{0x61}, std::byte{0x73}, std::byte{0x6d}, std::byte{0x01},
                                         std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x55}, std::byte{0x99}};
  const std::filesystem::path invalid_path{"/mobagen-smoke/invalid.plugin.wasm"};
  check(stage_file(invalid_path, invalid_bytes), "invalid bytes staged onto MEMFS");

  auto invalid = load_portable_wasm_plugin_binary(invalid_path, backend);
  bool invalid_rejected = false;
  bool backend_failure = false;
  for (const auto& issue : invalid.issues) {
    invalid_rejected = true;
    if (issue.code == PortableWasmPluginLoadIssueCode::BackendFailure) {
      backend_failure = true;
      std::printf("[browser-smoke]   invalid-bytes issue: %s\n", issue.message.c_str());
    }
  }
  check(invalid_rejected && !invalid.ok(), "invalid wasm bytes yielded a load issue (no crash)");
  check(backend_failure, "invalid wasm bytes mapped to the BackendFailure issue code");

  /* 3. Todo 14: web memory shim — MemoryManager (UNCHANGED algorithm code)
   *    over the WebShim inside THIS node worker agent.
   *
   *    - SHARED variant: the emscripten heap is SAB-backed (the runner's
   *      bundle check proves shared:true), so Atomics.load/store/CAS on the
   *      HEAP32 view are real cross-agent atomics and word_wait's worker
   *      path exercises a real blocking Atomics.wait (this bundle is booted
   *      inside a worker_threads Worker by scripts/smoke_web.mjs — a worker
   *      agent, where Atomics.wait is legal; plan todo 14 threading rule).
   *      Exercises: alloc offsets non-null, handles, roots, collect stats
   *      (marked == keep count, swept == garbage count), resolve
   *      round-trip, AND the bounded-poll fallback via the force-main test
   *      hook (main-thread participation path), then the threading-rule
   *      counters: main-thread blocking waits must be ZERO.
   *    - ISOLATED variant: MOBAGEN_WEB_SHARED undefined — the shim runs the
   *      single-context fallback (plain u32 atomics, no-op-yield waits, loud
   *      degradation note). Same manager flow on the main thread; the
   *      wait-call counter must stay ZERO because the isolated path never
   *      calls Atomics.wait at all. */
  {
    auto shim_owner = mobagen::memory::make_web_shim();
    check(shim_owner != nullptr, "web memory shim constructed");
    if (shim_owner != nullptr) {
      mobagen::memory::MemoryManager manager{shim_owner->shim()};
      check(manager.init(256U * 1024U), "memory manager initialized over the web shim");
      check(manager.region_size() >= 256U * 1024U, "web shim region acquired with the requested minimum");

      /* --- alloc/handle/root --- */
      const auto keep = manager.alloc(64, 2);
      check(keep != mobagen::memory::null_offset, "web shim: alloc returned a non-null block offset");
      std::uint32_t child_payload = 0;
      const auto child = manager.alloc(16, 0);
      if (child != mobagen::memory::null_offset) {
        std::memcpy(manager.payload(child), &child_payload, sizeof(child_payload));
      }
      const auto keep_handle = manager.handle_for(keep);
      const auto child_handle = manager.handle_for(child);
      check(keep_handle != mobagen::memory::null_handle && child_handle != mobagen::memory::null_handle, "web shim: handles bound to both blocks");
      check(manager.register_root(keep_handle) == keep_handle, "web shim: root registered for the keep object");
      if (child != mobagen::memory::null_offset) {
        /* Ref word: keep -> child, so the graph survives the sweep together. */
        std::memcpy(manager.payload(keep), &child_handle, sizeof(child_handle));
      }
      check(manager.root_count() == 1, "web shim: one registered root");

      /* --- resolve round-trip --- */
      const auto resolved_keep = manager.handle_resolve(keep_handle);
      check(resolved_keep == keep, "web shim: handle resolves back to the block offset");
      if (resolved_keep != mobagen::memory::null_offset) {
        std::uint32_t observed = 0;
        std::memcpy(&observed, manager.payload(keep), sizeof(observed));
        check(observed == child_handle, "web shim: payload write survives the resolve round-trip");
      }

      /* --- garbage + collect --- */
      const auto garbage = manager.alloc(32, 0);
      check(garbage != mobagen::memory::null_offset, "web shim: garbage allocated");
      const auto garbage_handle = manager.handle_for(garbage);
      check(garbage_handle != mobagen::memory::null_handle, "web shim: garbage handle bound before collect");
      check(manager.live_objects() == 3, "web shim: three live objects before collect");

      mobagen::memory::CollectStats stats{};
      check(manager.collect(&stats), "web shim: stop-the-world collect ran through the shim");
      check(stats.marked == 2, "web shim: collect marked the root and its ref (stats observable)");
      check(stats.swept == 1, "web shim: collect swept the unreachable garbage");
      check(manager.live_objects() == 2, "web shim: live count is 2 after collect");
      check(manager.handle_resolve(garbage_handle) == mobagen::memory::null_offset,
            "web shim: handle of the swept garbage is dead (generation bumped on release)");

      /* post-collect resolve still round-trips */
      check(manager.handle_resolve(keep_handle) == keep, "web shim: keep handle still resolves after collect");

      /* --- threading-rule instrumentation (plan todo 14, verbatim) --- */
      const bool shared_variant = mobagen::memory::WebShim::shared_variant();
      const auto main_thread_waits = mobagen::memory::WebShim::stats_main_thread_blocking_waits();
      check(main_thread_waits == 0, "web shim: main-thread Atomics.wait NEVER called (threading rule, counter==0)");
      const auto blocking_waits = mobagen::memory::WebShim::stats_blocking_waits();
      const auto poll_fallbacks = mobagen::memory::WebShim::stats_poll_fallback_calls();
      if (shared_variant) {
        /* Worker-hosted bundle: waits (if any ran) were executed by the
         * worker path; the isolated path never calls wait at all — either
         * way the rule holds: main == 0, and the totals partition. */
        check(true, "web shim: shared variant counters observable (waits ran on the worker path only)");
      } else {
        check(blocking_waits == 0, "web shim: isolated fallback never calls Atomics.wait (degraded no-op-yield path)");
      }

      /* --- drill (variant-aware) ---
       * SHARED: force the MAIN-thread classification; the next wait must
       * take the bounded-poll path (paced poll with a hard timeout — never
       * an unpaced spin, never Atomics.wait on the host agent). A word that
       * never changes + a 30 ms budget returns in bounded time with the
       * observed (unchanged) value; the poll-fallback counter must move.
       * ISOLATED: word_wait degrades to no-op-yield (returns the observed
       * value immediately, ignoring the budget) and fires the ONE loud
       * degradation note — asserted on the trace sink. */
      if (shared_variant) {
        mobagen::memory::WebShim::set_force_main_thread(true);
        const auto before_polls = mobagen::memory::WebShim::stats_poll_fallback_calls();
        const auto marker_start = shim_owner->shim().now_ns();
        const auto waited = shim_owner->shim().word_wait(MobagenAllocatorWord{32}, 0, 30);
        const auto elapsed_ms = (shim_owner->shim().now_ns() - marker_start) / 1000000ULL;
        mobagen::memory::WebShim::set_force_main_thread(false);
        const auto after_polls = mobagen::memory::WebShim::stats_poll_fallback_calls();
        check(waited == 0, "web shim: bounded-poll wait returned the observed (unchanged) word value");
        check(elapsed_ms >= 25 && elapsed_ms < 5000, "web shim: bounded-poll wait honored the timeout (paced, not instant)");
        check(after_polls > before_polls, "web shim: main-thread wait took the bounded-poll fallback path");
        check(mobagen::memory::WebShim::stats_main_thread_blocking_waits() == 0,
              "web shim: forced-main wait still executed ZERO main-thread Atomics.wait calls");
      } else {
        const auto before_polls = mobagen::memory::WebShim::stats_poll_fallback_calls();
        const auto waited = shim_owner->shim().word_wait(MobagenAllocatorWord{32}, 0, 30);
        check(waited == 0, "web shim: isolated wait returned the observed word value (no-op-yield)");
        check(mobagen::memory::WebShim::stats_poll_fallback_calls() == before_polls,
              "web shim: isolated wait path never reaches the poll fallback (no blocking at all)");
        bool isolated_note = false;
        for (const auto& entry : shim_owner->trace_log()) {
          if (entry.find("ISOLATED variant") != std::string::npos) isolated_note = true;
        }
        check(isolated_note, "web shim: isolated degradation note traced exactly once (loud)");
      }

      const char* first_trace = shim_owner->trace_log().empty() ? "(no shim trace entries)" : shim_owner->trace_log().front().c_str();
      /* Exact-marker lines (the runner matches full lines verbatim) + the
       * detailed diagnostics line after them. */
      std::printf("[browser-smoke] memory-shim-counters variant=%s\n", shared_variant ? "shared" : "isolated");
      std::printf("[browser-smoke] memory-shim-counters variant=%s blocking=%u main=%u poll=%u\n", shared_variant ? "shared" : "isolated",
                  blocking_waits, main_thread_waits, poll_fallbacks);
      std::printf("[browser-smoke] memory-shim-trace %s\n", first_trace);
    }
  }

  /* 4. Todo 16: the QuickJS scripting guest through the same production
     loader pipeline — load, activate, evaluate `1+1` through the typed
     descriptor dispatcher, assert the {"ok":true,"value":"2"} envelope, and
     a syntax error surfacing as a module issue (envelope), never a crash. */
  {
    const std::span<const std::byte> quickjs{reinterpret_cast<const std::byte*>(mobagen_quickjs_guest_wasm), mobagen_quickjs_guest_wasm_bytes};
    check(quickjs.size() < browser_wasm_sync_compile_budget_bytes, "QuickJS guest under the 8MB sync-compile budget");
    const std::filesystem::path quickjs_path{"/mobagen-smoke/quickjs.plugin.wasm"};
    check(stage_file(quickjs_path, quickjs), "QuickJS guest staged onto MEMFS");

    auto quickjs_loaded = load_portable_wasm_plugin_binary(quickjs_path, backend);
    check(quickjs_loaded.ok(), "QuickJS guest loaded through BrowserWasmBackend (sync instantiate + descriptor query)");
    if (!quickjs_loaded.ok() && !quickjs_loaded.issues.empty()) {
      std::printf("[browser-smoke]   load issue: %s\n", quickjs_loaded.issues.front().message.c_str());
    }
    if (quickjs_loaded.ok() && quickjs_loaded.plugin.has_value()) {
      check(quickjs_loaded.plugin->provider().id == "mobagen.scripting.quickjs", "QuickJS provider id matches the guest descriptor");

      auto quickjs_activated = activate_portable_wasm_plugin(quickjs_loaded.plugin->take_instance());
      check(quickjs_activated.ok(), "QuickJS guest activated (host imports bound, configure + start)");
      if (quickjs_activated.ok() && quickjs_activated.activation != nullptr) {
        /* Build the eval marshaling descriptor from the guest's own
           annotation table (read live from the mirror, same as the
           reference guest above). */
        std::vector<mobagen::modules::ModuleManifestExport> quickjs_exports;
        /* The instance is owned by the activation; re-load a fresh instance
           for the raw table read + direct typed invokes, then run the same
           evals through the activation's lifecycle-clean second instance. */
        auto direct = backend.instantiate(quickjs, nullptr);
        check(direct.ok(), "QuickJS direct instance instantiated for typed eval");
        if (direct.ok()) {
          /* The typed invokes below need the lifecycle driven on THIS
             instance (activate_portable_wasm_plugin owns its own). */
          auto direct_configured = direct.instance->invoke(WasmPluginExport::Configure, std::array<std::uint32_t, 2>{});
          check(direct_configured.ok() && *direct_configured.value == MOBAGEN_WASM_STATUS_OK, "QuickJS direct instance configured");
          auto direct_started = direct.instance->invoke(WasmPluginExport::Start, {});
          check(direct_started.ok() && *direct_started.value == MOBAGEN_WASM_STATUS_OK, "QuickJS direct instance started");
          const auto memory = direct.instance->memory();
          check(read_annotation_exports(memory.data(), memory.size(), quickjs_exports), "QuickJS annotation table read from live guest memory");
          const auto* eval_export = static_cast<const mobagen::modules::ModuleManifestExport*>(nullptr);
          for (const auto& entry : quickjs_exports) {
            if (entry.name == "mobagen_scripting_eval_v1") eval_export = &entry;
          }
          check(eval_export != nullptr && eval_export->marshaling.has_value(), "mobagen_scripting_eval_v1 descriptor decoded");

          if (eval_export != nullptr && eval_export->marshaling.has_value()) {
            const std::string source = "1+1";
            auto writable = direct.instance->writable_memory();
            check(writable.size() >= 65536, "QuickJS guest memory writable for span staging");
            /* Stage through the guest's own allocate export: the emcc layout
               places the guest's exchange arena ABOVE quickjs's globals, so
               hardcoded low offsets would trample engine state. */
            const std::array allocate_arguments{std::uint32_t{4096}, MOBAGEN_WASM_EXCHANGE_ALIGNMENT};
            auto scratch_allocation = direct.instance->invoke(WasmPluginExport::Allocate, allocate_arguments);
            const bool scratch_ok = scratch_allocation.ok() && *scratch_allocation.value != MOBAGEN_WASM_NULL_OFFSET;
            const std::uint32_t scratch = scratch_ok ? *scratch_allocation.value : 0;
            /* Re-take the writable view AFTER the allocate invoke: the
               invoke flushed the mirror and cleared the dirty flag, and
               writes through the older view would never be flushed. */
            auto arena = direct.instance->writable_memory();
            check(scratch_ok, "QuickJS exchange scratch allocated through the guest allocator");
            if (writable.size() >= 65536 && scratch_ok) {
              const std::uint32_t source_offset = scratch;
              const std::uint32_t result_offset = scratch + 1024;
              const std::uint32_t source_pair = scratch + 2048;
              const std::uint32_t result_pair = source_pair + 8;
              for (std::size_t index = 0; index < source.size(); ++index) {
                arena[source_offset + index] = std::byte{static_cast<std::uint8_t>(source[index])};
              }
              /* Full LE32 words: the emcc layout's arena sits above 64 KiB. */
              auto stage_pair = [&arena](std::uint32_t at, std::uint32_t offset, std::uint32_t size) {
                arena[at + 0] = std::byte{static_cast<std::uint8_t>(offset & 0xffU)};
                arena[at + 1] = std::byte{static_cast<std::uint8_t>((offset >> 8U) & 0xffU)};
                arena[at + 2] = std::byte{static_cast<std::uint8_t>((offset >> 16U) & 0xffU)};
                arena[at + 3] = std::byte{static_cast<std::uint8_t>((offset >> 24U) & 0xffU)};
                arena[at + 4] = std::byte{static_cast<std::uint8_t>(size & 0xffU)};
                arena[at + 5] = std::byte{static_cast<std::uint8_t>((size >> 8U) & 0xffU)};
                arena[at + 6] = std::byte{static_cast<std::uint8_t>((size >> 16U) & 0xffU)};
                arena[at + 7] = std::byte{static_cast<std::uint8_t>((size >> 24U) & 0xffU)};
              };
              stage_pair(source_pair, source_offset, static_cast<std::uint32_t>(source.size()));
              stage_pair(result_pair, result_offset, 1024);

              std::array<std::uint32_t, 2> result_cells{};
              const std::array eval_cells{source_pair, result_pair};
              const auto dispatched
                  = browser_wasm_invoke_typed_export(*direct.instance, eval_export->name, *eval_export->marshaling, eval_cells, result_cells);
              check(dispatched == 0, "QuickJS eval dispatched through the generic descriptor marshaller");
              check(dispatched == 0 && result_cells[0] == MOBAGEN_WASM_STATUS_OK, "QuickJS eval(1+1) export returned OK");
              if (dispatched == 0 && result_cells[0] == MOBAGEN_WASM_STATUS_OK) {
                const auto view = direct.instance->memory();
                const char* text = reinterpret_cast<const char*>(view.data() + result_offset);
                std::string envelope{text, strnlen(text, 64)};
                std::printf("[browser-smoke] quickjs-eval %s\n", envelope.c_str());
                check(envelope.find("\"ok\":true") != std::string::npos, "QuickJS eval(1+1) envelope reports ok:true");
                check(envelope.find("\"value\":\"2\"") != std::string::npos, "QuickJS eval(1+1) returned 2");
              }

              /* Failure path: a JS syntax error is a module issue inside the
                 result envelope — guest keeps running, host never crashes.
                 The first dispatch flushed the mirror; re-take the writable
                 view so the new staging is marked dirty and flushed. */
              auto arena2 = direct.instance->writable_memory();
              const std::string broken = "function {{{";
              for (std::size_t index = 0; index < broken.size(); ++index) {
                arena2[source_offset + index] = std::byte{static_cast<std::uint8_t>(broken[index])};
              }
              arena2[source_pair + 4] = std::byte{static_cast<std::uint8_t>(broken.size())};
              std::array<std::uint32_t, 2> broken_cells{};
              const std::array broken_eval_cells{source_pair, result_pair};
              const auto broken_dispatched
                  = browser_wasm_invoke_typed_export(*direct.instance, eval_export->name, *eval_export->marshaling, broken_eval_cells, broken_cells);
              check(broken_dispatched == 0 && broken_cells[0] == MOBAGEN_WASM_STATUS_OK, "QuickJS syntax-error eval completed (no crash)");
              if (broken_dispatched == 0 && broken_cells[0] == MOBAGEN_WASM_STATUS_OK) {
                const auto view = direct.instance->memory();
                const char* text = reinterpret_cast<const char*>(view.data() + result_offset);
                std::string envelope{text, strnlen(text, 64)};
                std::printf("[browser-smoke] quickjs-syntax-error %s\n", envelope.c_str());
                check(envelope.find("\"ok\":false") != std::string::npos, "QuickJS syntax error surfaced as ok:false in the envelope");
                check(envelope.find("SyntaxError") != std::string::npos, "QuickJS syntax error names SyntaxError");
              }
            }
            auto direct_quiesced = direct.instance->invoke(WasmPluginExport::Quiesce, {});
            auto direct_stopped = direct_quiesced.ok() ? direct.instance->invoke(WasmPluginExport::Stop, {}) : direct_quiesced;
            check(direct_stopped.ok(), "QuickJS direct instance quiesced + stopped");
            if (scratch_ok) {
              const std::array deallocate_arguments{scratch, std::uint32_t{4096}, MOBAGEN_WASM_EXCHANGE_ALIGNMENT};
              (void)direct.instance->invoke(WasmPluginExport::Deallocate, deallocate_arguments);
            }
            direct.instance.reset();
          }
        }

        auto quiesced = quickjs_activated.activation->quiesce();
        auto stopped = quiesced.ok() ? quickjs_activated.activation->stop() : quiesced;
        check(stopped.ok(), "QuickJS guest quiesced + stopped cleanly");
      }
    }
  }

  /* 4b. Todo 17: the Lua scripting guest through the same production loader
     pipeline — load, direct typed eval `2*21` -> 42 through the descriptor
     dispatcher, and a runtime error recovered through the trap + drain
     export pair (the browser divergence from QuickJS's in-band errors:
     a Lua error traps, then mobagen_scripting_error_v1 finishes the
     unwind and writes the ok:false envelope). */
  {
    const std::span<const std::byte> lua{reinterpret_cast<const std::byte*>(mobagen_lua_guest_wasm), mobagen_lua_guest_wasm_bytes};
    check(lua.size() < browser_wasm_sync_compile_budget_bytes, "Lua guest under the 8MB sync-compile budget");
    const std::filesystem::path lua_path{"/mobagen-smoke/lua.plugin.wasm"};
    check(stage_file(lua_path, lua), "Lua guest staged onto MEMFS");

    auto lua_loaded = load_portable_wasm_plugin_binary(lua_path, backend);
    check(lua_loaded.ok(), "Lua guest loaded through BrowserWasmBackend (sync instantiate + descriptor query)");
    if (!lua_loaded.ok() && !lua_loaded.issues.empty()) {
      std::printf("[browser-smoke]   load issue: %s\n", lua_loaded.issues.front().message.c_str());
    }
    if (lua_loaded.ok() && lua_loaded.plugin.has_value()) {
      check(lua_loaded.plugin->provider().id == "mobagen.scripting.lua", "Lua provider id matches the guest descriptor");

      auto lua_activated = activate_portable_wasm_plugin(lua_loaded.plugin->take_instance());
      check(lua_activated.ok(), "Lua guest activated (host imports bound, configure + start)");
      if (lua_activated.ok() && lua_activated.activation != nullptr) {
        std::vector<mobagen::modules::ModuleManifestExport> lua_exports;
        auto direct = backend.instantiate(lua, nullptr);
        check(direct.ok(), "Lua direct instance instantiated for typed eval");
        if (direct.ok()) {
          auto direct_configured = direct.instance->invoke(WasmPluginExport::Configure, std::array<std::uint32_t, 2>{});
          check(direct_configured.ok() && *direct_configured.value == MOBAGEN_WASM_STATUS_OK, "Lua direct instance configured");
          auto direct_started = direct.instance->invoke(WasmPluginExport::Start, {});
          check(direct_started.ok() && *direct_started.value == MOBAGEN_WASM_STATUS_OK, "Lua direct instance started");
          if (direct_configured.ok() && direct_started.ok()) {
            const auto memory = direct.instance->memory();
            check(read_annotation_exports(memory.data(), memory.size(), lua_exports), "Lua annotation table read from live guest memory");
            const mobagen::modules::ModuleManifestExport* eval_export = nullptr;
            const mobagen::modules::ModuleManifestExport* error_export = nullptr;
            for (const auto& entry : lua_exports) {
              if (entry.name == "mobagen_scripting_eval_v1") eval_export = &entry;
              if (entry.name == "mobagen_scripting_error_v1") error_export = &entry;
            }
            check(eval_export != nullptr && eval_export->marshaling.has_value(), "mobagen_scripting_eval_v1 descriptor decoded");
            check(error_export != nullptr && error_export->marshaling.has_value(), "mobagen_scripting_error_v1 descriptor decoded");

            if (eval_export != nullptr && eval_export->marshaling.has_value() && error_export != nullptr
                && error_export->marshaling.has_value()) {
              const std::array allocate_arguments{std::uint32_t{4096}, MOBAGEN_WASM_EXCHANGE_ALIGNMENT};
              auto scratch_allocation = direct.instance->invoke(WasmPluginExport::Allocate, allocate_arguments);
              const bool scratch_ok = scratch_allocation.ok() && *scratch_allocation.value != MOBAGEN_WASM_NULL_OFFSET;
              check(scratch_ok, "Lua guest scratch allocated through the allocate export");
              if (scratch_ok) {
                const std::uint32_t scratch = *scratch_allocation.value;
                /* Re-take writable_memory() AFTER the allocate invoke (view
                   invalidation rule) and write full LE32 words. */
                auto arena = direct.instance->writable_memory();
                const std::uint32_t source_offset = scratch;
                const std::uint32_t source_pair = scratch + 2048;
                const std::uint32_t result_pair = source_pair + 8;
                const std::uint32_t result_offset = scratch + 1024;
                const std::string source = "return 2*21";
                for (std::size_t index = 0; index < source.size(); ++index) {
                  arena[source_offset + index] = std::byte{static_cast<std::uint8_t>(source[index])};
                }
                auto stage_pair = [&arena](std::uint32_t at, std::uint32_t offset, std::uint32_t size) {
                  arena[at + 0] = std::byte{static_cast<std::uint8_t>(offset & 0xffU)};
                  arena[at + 1] = std::byte{static_cast<std::uint8_t>((offset >> 8U) & 0xffU)};
                  arena[at + 2] = std::byte{static_cast<std::uint8_t>((offset >> 16U) & 0xffU)};
                  arena[at + 3] = std::byte{static_cast<std::uint8_t>((offset >> 24U) & 0xffU)};
                  arena[at + 4] = std::byte{static_cast<std::uint8_t>(size & 0xffU)};
                  arena[at + 5] = std::byte{static_cast<std::uint8_t>((size >> 8U) & 0xffU)};
                  arena[at + 6] = std::byte{static_cast<std::uint8_t>((size >> 16U) & 0xffU)};
                  arena[at + 7] = std::byte{static_cast<std::uint8_t>((size >> 24U) & 0xffU)};
                };
                stage_pair(source_pair, source_offset, static_cast<std::uint32_t>(source.size()));
                stage_pair(result_pair, result_offset, 1024);

                std::array<std::uint32_t, 2> result_cells{};
                const std::array eval_cells{source_pair, result_pair};
                const auto dispatched
                    = browser_wasm_invoke_typed_export(*direct.instance, eval_export->name, *eval_export->marshaling, eval_cells, result_cells);
                check(dispatched == 0, "Lua eval dispatched through the generic descriptor marshaller");
                check(dispatched == 0 && result_cells[0] == MOBAGEN_WASM_STATUS_OK, "Lua eval(2*21) export returned OK");
                if (dispatched == 0 && result_cells[0] == MOBAGEN_WASM_STATUS_OK) {
                  const auto view = direct.instance->memory();
                  const char* text = reinterpret_cast<const char*>(view.data() + result_offset);
                  std::string envelope{text, strnlen(text, 64)};
                  std::printf("[browser-smoke] lua-eval %s\n", envelope.c_str());
                  check(envelope.find("\"ok\":true") != std::string::npos, "Lua eval(2*21) envelope reports ok:true");
                  check(envelope.find("\"value\":\"42\"") != std::string::npos, "Lua eval(2*21) returned 42");
                }

                /* Failure path: a Lua runtime error TRAPS the guest (the
                   trap-recovery divergence). The typed dispatch reports the
                   failure; re-take the writable view, re-stage the result
                   span, and drain through mobagen_scripting_error_v1. */
                auto arena2 = direct.instance->writable_memory();
                const std::string broken = "error('boom')";
                for (std::size_t index = 0; index < broken.size(); ++index) {
                  arena2[source_offset + index] = std::byte{static_cast<std::uint8_t>(broken[index])};
                }
                arena2[source_pair + 4] = std::byte{static_cast<std::uint8_t>(broken.size())};
                std::array<std::uint32_t, 2> broken_cells{};
                const std::array broken_eval_cells{source_pair, result_pair};
                const auto broken_dispatched
                    = browser_wasm_invoke_typed_export(*direct.instance, eval_export->name, *eval_export->marshaling, broken_eval_cells, broken_cells);
                check(broken_dispatched != 0, "Lua runtime-error eval surfaced as a failed invoke (trap)");
                if (broken_dispatched != 0) {
                  /* Re-stage the result span (full LE32 words; the trap
                     skipped the guest's own write of it). */
                  auto arena3 = direct.instance->writable_memory();
                  arena3[result_pair + 0] = std::byte{static_cast<std::uint8_t>(result_offset & 0xffU)};
                  arena3[result_pair + 1] = std::byte{static_cast<std::uint8_t>((result_offset >> 8U) & 0xffU)};
                  arena3[result_pair + 2] = std::byte{static_cast<std::uint8_t>((result_offset >> 16U) & 0xffU)};
                  arena3[result_pair + 3] = std::byte{static_cast<std::uint8_t>((result_offset >> 24U) & 0xffU)};
                  arena3[result_pair + 4] = std::byte{0};
                  arena3[result_pair + 5] = std::byte{4};
                  arena3[result_pair + 6] = std::byte{0};
                  arena3[result_pair + 7] = std::byte{0};
                  std::array<std::uint32_t, 2> error_cells{};
                  const std::array drain_cells{result_pair};
                  const auto drained
                      = browser_wasm_invoke_typed_export(*direct.instance, error_export->name, *error_export->marshaling, drain_cells, error_cells);
                  {
                    const auto dbg_view = direct.instance->memory();
                    std::printf("[browser-smoke] lua-drain dispatched=%d cells0=%u text=%s\n", drained, error_cells[0],
                                reinterpret_cast<const char*>(dbg_view.data() + result_offset));
                  }
                  check(drained == 0 && error_cells[0] == MOBAGEN_WASM_STATUS_OK, "Lua trap drained through mobagen_scripting_error_v1");
                  if (drained == 0 && error_cells[0] == MOBAGEN_WASM_STATUS_OK) {
                    const auto view = direct.instance->memory();
                    const char* text = reinterpret_cast<const char*>(view.data() + result_offset);
                    std::string envelope{text, strnlen(text, 128)};
                    std::printf("[browser-smoke] lua-trap-recovery %s\n", envelope.c_str());
                    check(envelope.find("\"ok\":false") != std::string::npos, "Lua runtime error surfaced as ok:false in the envelope");
                    check(envelope.find("boom") != std::string::npos, "Lua runtime error names the error() payload");
                  }

                  /* The guest still evaluates after the drain (recovered
                     state) — the recovery contract's core assertion. */
                  auto arena4 = direct.instance->writable_memory();
                  const std::string again = "return 6*7";
                  for (std::size_t index = 0; index < again.size(); ++index) {
                    arena4[source_offset + index] = std::byte{static_cast<std::uint8_t>(again[index])};
                  }
                  arena4[source_pair + 4] = std::byte{static_cast<std::uint8_t>(again.size())};
                  std::array<std::uint32_t, 2> again_cells{};
                  const std::array again_eval_cells{source_pair, result_pair};
                  const auto again_dispatched
                      = browser_wasm_invoke_typed_export(*direct.instance, eval_export->name, *eval_export->marshaling, again_eval_cells, again_cells);
                  check(again_dispatched == 0 && again_cells[0] == MOBAGEN_WASM_STATUS_OK, "Lua eval after trap recovery completed");
                  if (again_dispatched == 0 && again_cells[0] == MOBAGEN_WASM_STATUS_OK) {
                    const auto view = direct.instance->memory();
                    const char* text = reinterpret_cast<const char*>(view.data() + result_offset);
                    std::string envelope{text, strnlen(text, 64)};
                    check(envelope.find("\"value\":\"42\"") != std::string::npos, "Lua eval after trap recovery returned 42");
                  }
                }

                const std::array deallocate_arguments{scratch, std::uint32_t{4096}, MOBAGEN_WASM_EXCHANGE_ALIGNMENT};
                (void)direct.instance->invoke(WasmPluginExport::Deallocate, deallocate_arguments);
              }
            }
            auto direct_quiesced = direct.instance->invoke(WasmPluginExport::Quiesce, {});
            auto direct_stopped = direct_quiesced.ok() ? direct.instance->invoke(WasmPluginExport::Stop, {}) : direct_quiesced;
            check(direct_stopped.ok(), "Lua direct instance quiesced + stopped");
            direct.instance.reset();
          }
        }

        auto lua_quiesced = lua_activated.activation->quiesce();
        auto lua_stopped = lua_quiesced.ok() ? lua_activated.activation->stop() : lua_quiesced;
        check(lua_stopped.ok(), "Lua guest quiesced + stopped cleanly");
      }
    }
  }

  /* 5. Todo 15: memory alloc/collect micro-benchmark — exercises the web shim
   *    for throughput (ops/sec) on the same platform the smoke boots on.
   *    Outputs exact-marker evidence lines for the runner to capture. */
  {
    constexpr std::uint32_t kPayload = 32;
    constexpr std::uint32_t kAllocs = 10000;
    constexpr std::uint32_t kCollects = 500;
    constexpr std::uint32_t kWarmup = 3;
    constexpr std::uint32_t kSamples = 10;

    auto shim_owner = mobagen::memory::make_web_shim();
    check(shim_owner != nullptr, "bench: web memory shim constructed for benchmark");
    if (shim_owner != nullptr) {
      /* --- alloc throughput --- */
      std::vector<double> alloc_times;
      for (std::uint32_t w = 0; w < kWarmup; ++w) {
        mobagen::memory::MemoryManager mgr{shim_owner->shim()};
        mgr.init(256U * 1024U);
        for (std::uint32_t i = 0; i < kAllocs; ++i) mgr.alloc(kPayload, 0);
      }
      for (std::uint32_t s = 0; s < kSamples; ++s) {
        mobagen::memory::MemoryManager mgr{shim_owner->shim()};
        mgr.init(256U * 1024U);
        const auto t0 = std::chrono::steady_clock::now();
        for (std::uint32_t i = 0; i < kAllocs; ++i) mgr.alloc(kPayload, 0);
        const auto t1 = std::chrono::steady_clock::now();
        alloc_times.push_back(std::chrono::duration<double, std::nano>(t1 - t0).count());
      }
      std::sort(alloc_times.begin(), alloc_times.end());
      const double alloc_med = alloc_times[alloc_times.size() / 2];
      const double alloc_ops = static_cast<double>(kAllocs) / (alloc_med * 1e-9);
      std::printf("[browser-smoke] mem-bench alloc-32B median=%.0f ns ops/sec=%.0f\n", alloc_med, alloc_ops);

      /* --- collect throughput --- */
      std::vector<double> collect_times;
      for (std::uint32_t w = 0; w < kWarmup; ++w) {
        mobagen::memory::MemoryManager mgr{shim_owner->shim()};
        mgr.init(256U * 1024U);
        for (std::uint32_t i = 0; i < kAllocs; ++i) mgr.alloc(kPayload, 0);
        for (std::uint32_t i = 0; i < kCollects; ++i) mgr.collect();
      }
      for (std::uint32_t s = 0; s < kSamples; ++s) {
        mobagen::memory::MemoryManager mgr{shim_owner->shim()};
        mgr.init(256U * 1024U);
        for (std::uint32_t i = 0; i < kAllocs; ++i) mgr.alloc(kPayload, 0);
        const auto t0 = std::chrono::steady_clock::now();
        for (std::uint32_t i = 0; i < kCollects; ++i) mgr.collect();
        const auto t1 = std::chrono::steady_clock::now();
        collect_times.push_back(std::chrono::duration<double, std::nano>(t1 - t0).count());
      }
      std::sort(collect_times.begin(), collect_times.end());
      const double collect_med = collect_times[collect_times.size() / 2];
      const double collect_ops = static_cast<double>(kCollects) / (collect_med * 1e-9);
      std::printf("[browser-smoke] mem-bench collect-32B median=%.0f ns ops/sec=%.0f\n", collect_med, collect_ops);
      std::printf("[browser-smoke] mem-bench-done variant=%s\n", mobagen::memory::WebShim::shared_variant() ? "shared" : "isolated");
    }
  }

  if (failures == 0) std::printf("browser-backend-smoke-ok\n");
  return failures == 0 ? 0 : 1;
}
